In [6]:
from pybaseball import batting_stats_bref
import pandas as pd
import requests

In [80]:
# get LA sweet spot data stats from csv
launch_angle_data = pd.read_csv('launch_angle_data/savant_launch_angle_data.csv')

launch_angle_data = launch_angle_data[['last_name, first_name', 'sweet_spot_percent']]

In [ ]:
# get team wrc+ from fangraphs api

START = 2020
END = 2025

all_years = []

for year in range(START, END + 1):

    url = (
        f"https://www.fangraphs.com/api/leaders/major-league/data"
        f"?pos=all"
        f"&stats=bat"
        f"&lg=all"
        f"&qual=0"
        f"&season={year}"
        f"&season1={year}"
        f"&team=0,ts"
        f"&ind=0"
        f"&type=8"
        f"&pageitems=1000"
    )

    df = pd.read_json(url)

    rows = []

    for i in range(len(df)):

        team = df.iloc[i]["data"]   # one team dict

        rows.append({
            "Season": year,
            "Team": team["TeamNameAbb"],
            "wRC+": team["wRC+"]
        })

    all_years.append(pd.DataFrame(rows))

team_wrc = pd.concat(
    all_years,
    ignore_index=True
)

In [23]:
team_wrc

     Season Team        wRC+
0      2020  LAD  120.221187
1      2020  SDP  116.439079
2      2020  CHW  111.135002
3      2020  ATL  119.817551
4      2020  NYM  122.744579
..      ...  ...         ...
175    2025  WSN   92.809831
176    2025  LAA   91.598627
177    2025  PIT   82.200798
178    2025  CHW   88.475751
179    2025  COL   74.432996

[180 rows x 3 columns]

In [89]:
# figure out which players played for what team in each season

START = 2015
END = 2025

all_players = []

for year in range(START, END + 1):
    print(f"Loading {year}")

    # Baseball Reference player batting stats
    df = batting_stats_bref(year)
    
    print(df.iloc[2])

    df["Season"] = year
    
    # fix decoding errors
    df["Name"] = (
        df["Name"]
        .apply(lambda x: bytes(x, "utf-8").decode("unicode_escape"))
        .str.encode("latin1")
        .str.decode("utf-8")
    )

    all_players.append(
        df[[
            "Name",
            "Season",
            "Tm",
            "PA",
        ]]
    )

players = pd.concat(all_players, ignore_index=True)

print(players)

players.to_csv('player_team_data.csv')

player_team_year = pd.read_csv('player_team_data.csv', index_col=0)

Loading 2015
Name        Dustin Ackley
Age                    27
#days                3881
Lev                Maj-AL
Tm       New York,Seattle
G                     100
PA                    264
AB                    238
R                      28
H                      55
2B                     11
3B                      3
HR                     10
RBI                    30
BB                     18
IBB                     0
SO                     45
HBP                     1
SH                      3
SF                      4
GDP                     3
SB                      2
CS                      2
BA                  0.231
OBP                 0.284
SLG                 0.429
OPS                 0.712
mlbID              554429
Name: 3, dtype: object
Loading 2016
Name     Dustin Ackley
Age                 28
#days             3643
Lev             Maj-AL
Tm            New York
G                   25
PA                  70
AB                  61
R                    6
H                    9
2B                   0
3B                   0
HR                   0
RBI                  4
BB                   8
IBB                  0
SO                   9
HBP                  0
SH                   0
SF                   1
GDP                  0
SB                   0
CS                   0
BA               0.148
OBP              0.243
SLG              0.148
OPS               0.39
mlbID           554429
Name: 3, dtype: object
Loading 2017
Name     Lane Adams
Age              27
#days          3153
Lev          Maj-NL
Tm          Atlanta
G                82
PA              122
AB              109
R                19
H                30
2B                4
3B                1
HR                5
RBI              20
BB               10
IBB               0
SO               37
HBP               1
SH                1
SF                1
GDP               3
SB               10
CS                0
BA            0.275
OBP           0.339
SLG           0.468
OPS           0.807
mlbID        572669
Name: 3, dtype: object
Loading 2018
Name     Willy Adames
Age                22
#days            2789
Lev            Maj-AL
Tm          Tampa Bay
G                  85
PA                323
AB                288
R                  43
H                  80
2B                  7
3B                  0
HR                 10
RBI                34
BB                 31
IBB                 3
SO                 95
HBP                 1
SH                  1
SF                  2
GDP                 6
SB                  6
CS                  5
BA              0.278
OBP             0.348
SLG             0.406
OPS             0.754
mlbID          642715
Name: 3, dtype: object
Loading 2019
Name     Cristhian Adames
Age                    27
#days                2425
Lev                Maj-NL
Tm          San Francisco
G                      10
PA                     24
AB                     22
R                       1
H                       7
2B                      1
3B                      0
HR                      0
RBI                     2
BB                      2
IBB                     0
SO                      8
HBP                     0
SH                      0
SF                      0
GDP                     0
SB                      0
CS                      0
BA                  0.318
OBP                 0.375
SLG                 0.364
OPS                 0.739
mlbID              542436
Name: 3, dtype: object
Loading 2020
Name     Willy Adames
Age                24
#days            2062
Lev            Maj-AL
Tm          Tampa Bay
G                  54
PA                205
AB                185
R                  29
H                  48
2B                 15
3B                  1
HR                  8
RBI                23
BB                 20
IBB                 0
SO                 74
HBP                 0
SH                  0
SF                  0
GDP                 4
SB                  2
CS                  1
BA              0.259
OBP             0.332
SLG             0.481
OPS             0.813
mlbID          642715
Name: 3, dtype: object
Loading 2021
Name     Ronald Acu\xc3\xb1a Jr.
Age                           23
#days                       1775
Lev                       Maj-NL
Tm                       Atlanta
G                             82
PA                           360
AB                           297
R                             72
H                             84
2B                            19
3B                             1
HR                            24
RBI                           52
BB                            49
IBB                            2
SO                            85
HBP                            9
SH                             0
SF                             5
GDP                            0
SB                            17
CS                             6
BA                         0.283
OBP                        0.394
SLG                        0.596
OPS                         0.99
mlbID                     660670
Name: 3, dtype: object
Loading 2022
Name     Ronald Acu\xc3\xb1a Jr.
Age                           24
#days                       1313
Lev                       Maj-NL
Tm                       Atlanta
G                            123
PA                           550
AB                           482
R                             73
H                            129
2B                            25
3B                             0
HR                            15
RBI                           50
BB                            54
IBB                            4
SO                           131
HBP                           11
SH                             0
SF                             3
GDP                            8
SB                            29
CS                            11
BA                         0.268
OBP                        0.353
SLG                        0.413
OPS                        0.766
mlbID                     660670
Name: 3, dtype: object
Loading 2023
Name     Wilyer Abreu
Age                24
#days             962
Lev            Maj-AL
Tm             Boston
G                  28
PA                 85
AB                 76
R                  10
H                  24
2B                  6
3B                  0
HR                  2
RBI                14
BB                  9
IBB                 0
SO                 23
HBP                 0
SH                  0
SF                  0
GDP                 0
SB                  3
CS                  1
BA              0.316
OBP             0.388
SLG             0.474
OPS             0.862
mlbID          677800
Name: 3, dtype: object
Loading 2024
Name     Wilyer Abreu
Age                25
#days             598
Lev            Maj-AL
Tm             Boston
G                 132
PA                446
AB                398
R                  59
H                 101
2B                 33
3B                  2
HR                 15
RBI                58
BB                 40
IBB                 0
SO                125
HBP                 3
SH                  0
SF                  5
GDP                 7
SB                  8
CS                  3
BA              0.254
OBP             0.323
SLG              0.46
OPS             0.783
mlbID          677800
Name: 3, dtype: object
Loading 2025
Name     Maximo Acosta
Age                 22
#days              248
Lev             Maj-NL
Tm               Miami
G                   19
PA                  61
AB                  54
R                    7
H                   11
2B                   1
3B                   0
HR                   3
RBI                  5
BB                   6
IBB                  0
SO                  17
HBP                  1
SH                   0
SF                   0
GDP                  0
SB                   1
CS                   2
BA               0.204
OBP              0.295
SLG              0.389
OPS              0.684
mlbID           691185
Name: 3, dtype: object
                  Name  Season                Tm   PA
0        David Aardsma    2015           Atlanta    1
1           José Abreu    2015           Chicago  668
2        Dustin Ackley    2015  New York,Seattle  264
3     Cristhian Adames    2015          Colorado   58
4         Austin Adams    2015         Cleveland    1
...                ...     ...               ...  ...
9204        Nick Yorke    2025        Pittsburgh   72
9205  Masataka Yoshida    2025            Boston  212
9206        Cole Young    2025           Seattle  257
9207       Jacob Young    2025        Washington  364
9208       Jared Young    2025          New York   47

[9209 rows x 4 columns]

In [83]:
player_team_year.head(3)
player_team_year[player_team_year['Name'] == "Dustin Ackley"]

              Name  Season                Tm   PA
2    Dustin Ackley    2015  New York,Seattle  264
967  Dustin Ackley    2016          New York   70

In [77]:
team_wrc.head(3)

   Season Team        wRC+
0    2020  LAD  120.221187
1    2020  SDP  116.439079
2    2020  CHW  111.135002

In [81]:
launch_angle_data.head(3)

  last_name, first_name  sweet_spot_percent
0        Colon, Bartolo                23.1
1         Hunter, Torii                28.5
2          Ortiz, David                34.8